source 'https://rubygems.org'
ruby '>= 3.1'

# Web framework and server dependencies
gem 'sinatra', '~> 4.1.1'
gem 'rack', '~> 3.0'
gem 'sinatra-contrib', '~> 4.1.0'  # Matches sinatra 4.1.1
gem 'puma', '~> 6.4'              # Puma web server
gem 'rack-cors', '~> 2.0.0'       # Cross-origin resource sharing
gem 'rackup', '~> 2.1'
# File and document processing
gem 'csv'                         # CSV processing (stdlib, no version needed)
gem 'prawn', '~> 2.4'             # PDF generation
gem 'prawn-table', '~> 0.2'       # Tables for Prawn
gem 'caxlsx', '~> 4.1'            # Excel file generation
gem 'fiddle'
group :development, :test do
  gem 'rspec', '~> 3.12.0'        # Testing framework
  gem 'rack-test', '~> 2.1.0'     # Rack testing utilities
end