source "https://rubygems.org"

ruby ">= 3.1.0"

gem "sinatra", require: "sinatra/base"
gem "sinatra-contrib"
gem "puma"
gem "csv"
gem "json"
gem "prawn"
gem "prawn-table"
gem "gruff"
gem "axlsx"

group :development, :test do
  gem "rspec"
  gem "rack-test"
end
