source "https://rubygems.org"

ruby ">= 3.1.0"

gem "sinatra", require: "sinatra/base"
gem "sinatra-contrib"
gem "puma"
gem "prawn"
gem "prawn-table"
gem "caxlsx"
gem "rubyzip"
gem "rake"

# Optional dependencies - graceful degradation if not available
begin
  gem "gruff"
rescue LoadError
  # gruff requires ImageMagick, continue without it
end

group :development, :test do
  gem "rspec"
  gem "rack-test"
  gem "sinatra-reloader"
end
